name: integration

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  test-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim-version: [stable, nightly]
    steps:
      - uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}

      - uses: extractions/setup-just@v2

      - run: sudo apt-get update && sudo apt-get install -y fzf

      - run: just test-integration
